name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16, 18]

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2

            - uses: ./.github/actions/setup-and-cache
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install & Build
              run: |
                  pnpm install
                  pnpm exec playwright install
                  pnpm build

            - name: Lint
              run: pnpm lint

            - name: Typecheck
              run: pnpm typecheck

            - name: Unit Tests
              run: pnpm test

            - name: Integration Tests
              run: pnpm test:integration

            - name: Documentation Tests
              run: |
                  pnpm docs:build
                  pnpm test:docs
