name: CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14, 16]

        steps:
            - uses: actions/checkout@v2

            - uses: ./.github/actions/setup-and-cache
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install & Build
              run: |
                  yarn install
                  yarn build

            - name: Lint
              run: yarn lint

            - name: Unit Tests
              run: yarn test

            - name: Integration Tests
              uses: cypress-io/github-action@v2
              with:
                  start: yarn test:integration
