name: Deploy docs

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: ./.github/actions/setup-and-cache

            - run: pnpm install
            - run: pnpm build
            - run: pnpm test
            - run: pnpm lint
            - run: pnpm docs:build
            - name: Deploy with gh-pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  pnpm docs:deploy -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
