name: Deploy docs

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install
            - run: yarn build
            - run: yarn test
            - run: yarn lint
            - run: yarn docs:build
            - run: yarn docs:deploy
