name: Deploy docs

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install
            - run: yarn build
            - run: yarn test
            - run: yarn lint
            - run: yarn docs:build
            - name: Deploy with gh-pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  yarn docs:deploy -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
